# src/BrainStream/Bundle/NylasBundle/Resources/config/oro/system_configuration.yml
system_configuration:
  groups:
    nylas_settings:
      title: "Nylas Settings"
      icon: "fa-cogs"
      priority: 255
    nylas_configuration:
      title: "Configuration"
      icon: "fa-cog"

  fields:
    brainstream_nylas.client_id:
      data_type: string
      type: Symfony\Component\Form\Extension\Core\Type\TextType
      options:
        label: "Client ID"
        required: true
        resettable: true
        constraints:
          - NotBlank: ~

    brainstream_nylas.client_secret:
      data_type: string
      type: Symfony\Component\Form\Extension\Core\Type\TextType
      options:
        label: "Client Secret"
        required: true
        resettable: true
        constraints:
          - NotBlank: ~

    brainstream_nylas.region:
      data_type: string
      type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
      options:
        label: "Region"
        required: true
        resettable: true
        choices:
          "US": "US"
          "EU": "EU"
        constraints:
          - NotBlank: ~

  tree:
    system_configuration:
      platform:
        children:
          integrations:
            children:
              nylas_settings:
                priority: 255
                children:
                  nylas_configuration:
                    priority: 100
                    children:
                      - brainstream_nylas.client_id
                      - brainstream_nylas.client_secret
                      - brainstream_nylas.region
